import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        
        <nav className="bg-white border-gray-200 dark:bg-gray-900">
          <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
            <a href="https://flowbite.com/" className="flex items-center">
                
                <span className="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Tactify</span>
            </a>
            <button data-collapse-toggle="navbar-default" type="button" className="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
              <span className="sr-only">Open main menu</span>
              <svg className="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
            </button>
            <div className="hidden w-full md:block md:w-auto" id="navbar-default">
              <ul className="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                <li>
                  <a href="#" className="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500" aria-current="page">Home</a>
                </li>
               
                <li>
                  <Link href={"/comunity-page"} className="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Comunity Page</Link>
                </li>
                <li>
                  <Link href={"/create-comp-page"} className="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Create Comp</Link>
                  
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <div className="flex flex-col items-center">
          <h1 className="text-6xl">Tactify</h1>
          <h2 className="text-slate-400">The Art of Winning in Team Fight Tactics</h2>
          <div className="flex flex-col w-96 border  rounded p-5 mt-4">
            <p>
              Welcome to Tactify, the ultimate guide to mastering the art of winning in Team Fight Tactics. Whether youre a seasoned player or just starting out, our expertly crafted composition strategies will help you dominate the competition.
            </p>
            <p className="mt-2">
              With Tactify, youll gain access to a comprehensive set of tactics and tips that will give you an edge in every game. From early-game decisions to late-game adaptations, weve got you covered with proven strategies that have been tested and refined by top TFT players.
            </p>
            <p className="mt-2">
              Our user-friendly interface makes it easy to browse and select the perfect composition for your playstyle, and our up-to-date information ensures that you always have the latest meta strategies at your fingertips.
            </p>

            <p className="mt-2">
              Join the Tactify community today and take your TFT game to the next level!
            </p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
